package libcafe.ui;

public class ActionPanel extends javax.swing.JPanel {
    
    /** Creates new form ActionPanel */
    public ActionPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addBookListButton = new javax.swing.JButton();
        addBorrowerButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        addBookListButton.setText("Add Book List");
        add(addBookListButton, new java.awt.GridBagConstraints());

        addBorrowerButton.setText("Add Borrower");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(addBorrowerButton, gridBagConstraints);

    }// </editor-fold>
    
    
    // Variables declaration - do not modify
    public javax.swing.JButton addBookListButton;
    public javax.swing.JButton addBorrowerButton;
    // End of variables declaration
    
}
