package libcafe.ui;

/**
*
* @author  Administrator
*/
public class BookListListUI extends javax.swing.JPanel {
   
   /** Creates new form BookListListUI */
   public BookListListUI() {
       initComponents();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
   private void initComponents() {
       jScrollPane1 = new javax.swing.JScrollPane();
       bookListList = new javax.swing.JList();

       setLayout(new java.awt.BorderLayout());

       bookListList.setModel(new javax.swing.AbstractListModel() {
           String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
           public int getSize() { return strings.length; }
           public Object getElementAt(int i) { return strings[i]; }
       });
       jScrollPane1.setViewportView(bookListList);

       add(jScrollPane1, java.awt.BorderLayout.CENTER);

   }// </editor-fold>
   
   
   // Variables declaration - do not modify
   public javax.swing.JList bookListList;
   private javax.swing.JScrollPane jScrollPane1;
   // End of variables declaration
   
}
