package libcafe.ui;

import javax.swing.JPanel;

public class BorrowerListUI extends JPanel {

	/** Creates new form BookListListUI */
	public BorrowerListUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		borrowerList = new javax.swing.JList();

		setLayout(new java.awt.BorderLayout());

		borrowerList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(borrowerList);

		add(jScrollPane1, java.awt.BorderLayout.CENTER);

	}// </editor-fold>

	// Variables declaration - do not modify
	public javax.swing.JList borrowerList;
	private javax.swing.JScrollPane jScrollPane1;

	// End of variables declaration

	public void setModel(BorrowerListModel controller) {
		borrowerList.setModel(controller);
	}
}
