package libcafe.ui;

/**
 * 
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form NewJFrame */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		jSplitPane2 = new javax.swing.JSplitPane();
		bookListListPanel = new BookListListUI();
		borrowerListPanel = new BorrowerListUI();
		actionPanel = new ActionPanel();
		jPanel2 = new javax.swing.JPanel();
		jSplitPane3 = new javax.swing.JSplitPane();
		bookListTablePanel = new BookListTableUI();
		bookDetailPanel = new BookEditUI();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jPanel1.setLayout(new java.awt.BorderLayout());

		jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		jSplitPane2.setTopComponent(bookListListPanel);

		jSplitPane2.setRightComponent(borrowerListPanel);

		jPanel1.add(jSplitPane2, java.awt.BorderLayout.CENTER);

		javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
		jPanel1.add(actionPanel, java.awt.BorderLayout.SOUTH);

		jSplitPane1.setLeftComponent(jPanel1);

		jPanel2.setLayout(new java.awt.BorderLayout());

		jSplitPane3.setDividerLocation(600);

		// javax.swing.GroupLayout bookListTablePanelLayout = new
		// javax.swing.GroupLayout(bookListTablePanel);
		// bookListTablePanel.setLayout(bookListTablePanelLayout);
		// bookListTablePanelLayout.setHorizontalGroup(bookListTablePanelLayout.createParallelGroup(
		// javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
		// Short.MAX_VALUE));
		// bookListTablePanelLayout.setVerticalGroup(bookListTablePanelLayout.createParallelGroup(
		// javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 645,
		// Short.MAX_VALUE));
		jSplitPane3.setLeftComponent(bookListTablePanel);

		jSplitPane3.setRightComponent(bookDetailPanel);

		jPanel2.add(jSplitPane3, java.awt.BorderLayout.CENTER);

		jSplitPane1.setRightComponent(jPanel2);

		getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

		jSplitPane1.setDividerSize(5);
		jSplitPane2.setDividerSize(5);
		jSplitPane3.setDividerSize(5);
		setTitle("Lib-Cafe ver 0.1");
		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				MainFrame f = new MainFrame();
				f.setSize(1024, 768);
				f.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	public ActionPanel actionPanel;
	public BookEditUI bookDetailPanel;
	public BookListListUI bookListListPanel;
	public BookListTableUI bookListTablePanel;
	public BorrowerListUI borrowerListPanel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JSplitPane jSplitPane2;
	private javax.swing.JSplitPane jSplitPane3;
	// End of variables declaration

}